language: ruby

sudo: false
dist: trusty

script:
  - bundle exec rake rubocop
  - bundle exec rake test

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-head

gemfile:
  - Gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head

notifications:
  email: false
